INSERT INTO Artist (ArtistID, ArtistName, Country) VALUES
(1, 'The Beatles', 'UK'),
(2, 'Pink Floyd', 'UK'),
(3, 'Led Zeppelin', 'UK'),
(4, 'David Bowie', 'UK'),
(5, 'Fleetwood Mac', 'UK'),
(6, 'The Rolling Stones', 'UK'),
(7, 'Nirvana', 'USA'),
(8, 'Jimi Hendrix', 'USA'),
(9, 'The Doors', 'USA'),
(10, 'Bob Dylan', 'USA'),
(11, 'Elton John', 'UK'),
(12, 'Queen', 'UK'),
(13, 'The Clash', 'UK'),
(14, 'Bruce Springsteen', 'USA'),
(15, 'Janis Joplin', 'USA'),
(16, 'Joy Division', 'UK'),
(17, 'Simon & Garfunkel', 'USA'),
(18, 'Aretha Franklin', 'USA'),
(19, 'The Smiths', 'UK'),
(20, 'The Velvet Underground', 'USA');
